server.port=8080
spring.datasource.url=jdbc:h2:file:./data/secuaudit;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.web.resources.static-locations=classpath:/static/
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
